server {
    listen 80;
    server_name _;

    location /signature/ {
        alias /usr/share/nginx/html/signature/;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=31536000, immutable";
        expires 1y;
    }

    location / {
        return 404 "Not found";
    }
}
